require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3.3

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
