require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3.3

Metrics/LineLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
